TEMP_SKIN_SURFACE_AVG = 93.2
MOISTURE_SKIN_STARTING = 0.75

SKIN_WOUND_INTEGRITY_PENALTY = 0.05
SKIN_WOUND_LEVELS = 4
SKIN_MAX_SWEAT = 6
SKIN_MAX_BLOOD = 4
SKIN_MAX_MOISTURE = SKIN_MAX_SWEAT + SKIN_WOUND_LEVELS + SKIN_MAX_BLOOD
SKIN_MAX_WAX = 3
SKIN_MAX_TEMPERATURE = 100.0
SKIN_MIN_TEMPERATURE = 91.0

WOUND_HEAT_SCALE = 2.0